# SIA81xx smart PA driver (ported from MTK BSP, tuning disabled)
snd-soc-sia81xx-objs := \
		sia81xx.o \
		sia81xx_regmap.o \
		sia81xx_aux_dev_if.o \
		sia81xx_set_vdd.o \
		sia8101_regs.o \
		sia8108_regs.o \
		sia8109_regs.o \
		sia8152_regs.o \
		sia8152s_regs.o \
		sia8159_regs.o \
		sia81xx_timer_task.o

obj-$(CONFIG_SND_SOC_SIA81XX) += snd-soc-sia81xx.o
