ccflags-y += -std=gnu99 -Wno-declaration-after-statement

obj-$(CONFIG_GXCODEC) += gxcodec.o

gxcodec-y += gxcodec_main.o
gxcodec-y += gxcodec_i2c.o
gxcodec-y += gxcodec_spi.o
gxcodec-y += gxcodec_upgrade.o
gxcodec-y += adpcm.o
