# SPDX-License-Identifier: GPL-2.0-only

# SPDX-License-Identifier: GPL-2.0-only

# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_TOUCHSCREEN_NT36XXX) += nt36xxx_driver.o

nt36xxx_driver-objs := nt36xxx.o \
                       nt36xxx_ext_proc.o \
                       nt36xxx_mp_ctrlram.o \
                       nt36xxx_fw_update.o
